CREATE DATABASE LOJA_2
GO

USE LOJA_2
GO

CREATE TABLE TB_FORN(
	ID_FORN INT IDENTITY (1,1),
	NM_FORN VARCHAR (200) NOT NULL,
	NR_CNPJ NUMERIC (14) NOT NULL,
	PRIMARY KEY (ID_FORN)
)

CREATE TABLE TB_PRODUTO(
	ID_PRODUTO INT IDENTITY (1,1),
	NM_PRODUTO VARCHAR (20) NOT NULL,
	PR_PRODUTO NUMERIC (6,2) NOT NULL,
	PR_VENDA NUMERIC (6,2),
	DT_CADASTRO DATE,
	ID_FORN INT,
	FOREIGN KEY (ID_FORN)
	REFERENCES TB_FORN (ID_FORN),
	PRIMARY KEY (ID_PRODUTO)
)