-- Inserindo dados...
-- Categ
INSERT INTO TB_CATEG(DS_CATEG) VALUES ('Padaria');
INSERT INTO TB_CATEG(DS_CATEG) VALUES ('Açougue');

SELECT * FROM TB_CATEG -- Apenas para teste

-- SubCateg
INSERT INTO TB_SUBCATEG(DS_SUBCATEG, ID_CATEG) VALUES ('Pão', 1);
INSERT INTO TB_SUBCATEG(DS_SUBCATEG, ID_CATEG) VALUES ('Pão', 1);
INSERT INTO TB_SUBCATEG(DS_SUBCATEG, ID_CATEG) VALUES ('Carne', 2);
INSERT INTO TB_SUBCATEG(DS_SUBCATEG, ID_CATEG) VALUES ('Carne', 2)

SELECT * FROM TB_SUBCATEG -- Apenas para teste

-- Produtos
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_SUBCATEG) VALUES ('Pão Frances', 1);
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_SUBCATEG) VALUES ('Carne Moída', 2);
